### ISSUE TITLE
can't find any download for macos, is there not one?

### ISSUE THREAD

**Issue by danik00111** [tomlin7/AoC#2]

**Comment by tomlin7** [comment]
@danik00111 The editor tool is a react app, so you can just clone the repo and proceed; or use the zipped build from release. 

For the notifier, can you try the macos builds provided here: https://github.com/tomlin7/AoC/actions/runs/12124766062

**Comment by tomlin7** [comment]
@danik00111 the macOS builds for notifier are now released, available here: https://github.com/tomlin7/AoC/releases/tag/v0.1.0
