### ISSUE TITLE
Database integration

### ISSUE THREAD

**Issue by adityakiran1423** [tomlin7/AoC#3]
Website shows options to choose from 2017-2024, why not add all the questions and their answers to a SQLite db? Schema would be pretty easy, something like :
```
erDiagram
    QUESTIONS {
        int year
        string part1question
        string part2question
        string part1answer
        string part2answer
    }
 ```

This schema is not normalised, however that can be looked after too, maybe using a NoSQL DB?

**Comment by tomlin7** [comment]
@adityakiran1423 sounds nice! as of now I have kept it as simple as possible, also #1 exists which is about adding auth and submission features. 

Adding such an archive will require solutions to all problems as well, organizing that much data will take a lot of time as well. Let me know your ideas to speed up this process.

**Comment by ArjixWasTaken** [comment]
![image](https://github.com/user-attachments/assets/bdcd11e5-3d71-4da5-9456-8a3dd2707ca4)
https://adventofcode.com/2024/about

**Comment by tomlin7** [comment]
@ArjixWasTaken thank you for pointing this out early! That makes clear, we can't store old puzzles in db and distribute it.
We can continue with the current method.

**Comment by adityakiran1423** [comment]
Aaah shit. I think now what can be done is that :
* We could scrape and add only that day's challenge on the left and let users add their code on the right for analysis.
* After that day it will automatically pre load the next day's challenge when it's out.

For the rest of the days of the year, maybe you could add like a counter for the next time AOC starts or something like that no?

**Comment by tomlin7** [comment]
@adityakiran1423 A counter sounds like a cool idea! yeah, we can easily do that using timestamps. Let's move this to a new issue.

**Comment by adityakiran1423** [comment]
Added @tomlin7 👍🏽

**Comment by ArjixWasTaken** [comment]
I'd assume it is fine to *modify* the real website using a browser extension, what if a browser extension was "enhancing" the UI of the original website?

That wouldn't be against the rules imo

**Comment by tomlin7** [comment]
@ArjixWasTaken iirc that would be fine. Terms say you shouldn't replicate the website and it's looks, copy content, republish content.
